### ISSUE TITLE
Variable "i" not defined in function "public static int crypto_box_keypair_with_seed(byte[] pk, byte[] sk, byte[] seed)"

### ISSUE THREAD

**Issue by sbaysting** [neilalexander/jnacl#10]
File: curve25519xsalsa20poly1305.java line 66. "i" isn't defined in the function or the class, causing the build to fail. I'm not sure how to fix it, but another library I'm using requires this one

**Comment by neilalexander** [comment]
Can you try reverting to commit 7da60ebb13c058b78af27b13f53f4ce3c909745b and see if the problem is resolved?

**Comment by sbaysting** [comment]
Yes, that does solve the problem

**Comment by neilalexander** [comment]
Thanks, the problem seemed to originate from a pull request. I have reverted it in commit 40c322e0a42637ab17cdf941138eeaf2494055f8 which will remove the offending function for now.
