### ISSUE TITLE
crypto_box_keypair Does not generate a keypair

### ISSUE THREAD

**Issue by paulrd** [neilalexander/jnacl#6]
When calling crypto_box_keypair(pk, sk), two non-random byte arrays are populated for pk (some deterministic series of bytes that do not use SecureRandom) and sk (all zeros).

**Comment by UCIS** [comment]
The code incorrectly initialized the public key buffer with random data, before overwriting it with the public key derived from the still uninitialized secret key buffer. The fix is trivial...
